sudo: required
services:
  - docker

before_install:
  - docker build -t vyeluri5/myapp .

script:
  - docker run -e CI=true vyeluri5/myapp npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-183596421493"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY